version: '2'

services:
   leaderboard_api:
      image: leaderboard_api
      ports:
         - "3000:3000"
   redis:
      image: "redis:alpine"
      restart: always
      ports:
         - "6379:6379"
      volumes:
         - $PWD/redis-data:/var/lib/redis
         - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
   mongodb:
      image: mongo
      restart: always
      environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: root
      ports:
         - 27017:27017
      volumes:
         - /var/lib/mongo:/data/db